CREATE TABLE Books (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,


    normalized_name TEXT,

    discussion_count INT,
    reviews_count INT,


);

CREATE TABLE Users (
    user_id SERIAL PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    -- email VARCHAR(255) NOT NULL UNIQUE,
    -- password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Reviews (
    review_id SERIAL PRIMARY KEY,
    user_id INT NOT NULL,  -- Foreign key from Users table
    book_id INT NOT NULL,  -- Foreign key from Books table
    review TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (book_id) REFERENCES Books(id),
    FOREIGN KEY (user_id) REFERENCES Users(user_id)  -- Assuming a Users table exists
);

CREATE TABLE Discussions (
    discuss_id SERIAL PRIMARY KEY,
    user_id INT NOT NULL,  -- Foreign key from Users table
    book_id INT NOT NULL,  -- Foreign key from Books table
    text TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (book_id) REFERENCES Books(id),
    FOREIGN KEY (user_id) REFERENCES Users(user_id)  -- Assuming a Users table exists
);


CREATE TABLE Replies (
    id SERIAL PRIMARY KEY,
    discuss_id INT NOT NULL,   -- Foreign key from Discussions table
    parent_id INT,            -- Self-referencing foreign key (can be NULL if it's a top-level reply)
    user_id INT NOT NULL,     -- Foreign key from Users table
    book_id INT NOT NULL,     -- Foreign key from Books table (optional based on your design)
    text TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (discuss_id) REFERENCES Discussions(discuss_id),
    FOREIGN KEY (parent_id) REFERENCES Replies(id),  -- Self-referencing for nested replies
    FOREIGN KEY (book_id) REFERENCES Books(id),
    FOREIGN KEY (user_id) REFERENCES Users(user_id)  -- Assuming a Users table exists
);


-- some data generated by ai for testing
INSERT INTO Books (name, author, description) VALUES
('The Catcher in the Rye', 'J.D. Salinger', 'A story about adolescent alienation.'),
('To Kill a Mockingbird', 'Harper Lee', 'A novel of warmth and humor despite dealing with serious issues of rape and racial inequality.'),
('1984', 'George Orwell', 'A dystopian social science fiction novel and cautionary tale about the dangers of totalitarianism.'),
('Pride and Prejudice', 'Jane Austen', 'A romantic novel that also critiques the British landed gentry at the end of the 18th century.'),
('Moby Dick', 'Herman Melville', 'The narrative of Captain Ahab’s obsessive quest to kill the white whale, Moby Dick.'),
('War and Peace', 'Leo Tolstoy', 'A novel that chronicles the French invasion of Russia and the impact of the Napoleonic era on Tsarist society.'),
('The Great Gatsby', 'F. Scott Fitzgerald', 'A novel about the decline of the American Dream in the 1920s.'),
('Crime and Punishment', 'Fyodor Dostoevsky', 'A novel about the mental anguish and moral dilemmas of an impoverished ex-student who kills a pawnbroker.'),
('Ulysses', 'James Joyce', 'A novel that parallels the events of Homer’s Odyssey in a modern context.'),
('The Odyssey', 'Homer', 'An epic poem that follows the Greek hero Odysseus on his journey home after the Trojan War.');


INSERT INTO Users (username) VALUES 
('alice_johnson'),
('bob_smith'),
('charlie_brown'),
('diana_prince'),
('evan_davis'),
('fiona_hall'),
('george_white'),
('hannah_lee'),
('ian_clark'),
('jane_doe');


-- Discussions for Book ID 1
INSERT INTO Discussions (user_id, book_id, text) VALUES
(1, 1, 'What do you think about Holdens character?'),
(2, 1, 'How does this novel compare to other coming-of-age stories?'),
(3, 1, 'Is the ending satisfying to you?');

-- Discussions for Book ID 2
INSERT INTO Discussions (user_id, book_id, text) VALUES
(4, 2, 'The trial scene was intense! Thoughts?'),
(5, 2, 'How does Scout’s perspective shape the story?'),
(6, 2, 'Lets talk about the symbolism of the mockingbird.');

-- Discussions for Book ID 3
INSERT INTO Discussions (user_id, book_id, text) VALUES
(7, 3, 'The themes of surveillance in 1984. What do you think?'),
(8, 3, 'How relevant is 1984 in todays society?'),
(9, 3, 'What are your thoughts on Big Brother?');



-- Replies to Discussion 1 of Book ID 1
INSERT INTO Replies (discuss_id, user_id, book_id, text) VALUES
(1, 2, 1, 'Holden is a complex character; he’s relatable yet frustrating.'),
(1, 3, 1, 'His contradictions make him real to me.'),
(1, 4, 1, 'I agree, he’s very well written.');

-- Replies to Discussion 2 of Book ID 1
INSERT INTO Replies (discuss_id, user_id, book_id, text) VALUES
(2, 5, 1, 'It’s unique because it doesn’t follow the typical formula.'),
(2, 6, 1, 'Other stories are more optimistic, this one is raw.'),
(2, 7, 1, 'It’s more introspective.');

-- Replies to Discussion 3 of Book ID 1
INSERT INTO Replies (discuss_id, user_id, book_id, text) VALUES
(3, 8, 1, 'The ending left me with more questions.'),
(3, 9, 1, 'It was open-ended, which I didn’t expect.'),
(3, 10, 1, 'I found it thought-provoking.');




-- Reviews for Book ID 1
INSERT INTO Reviews (user_id, book_id, review) VALUES
(1, 1, 'A gripping and thought-provoking novel.'),
(2, 1, 'I had mixed feelings, but overall it was a good read.');

-- Reviews for Book ID 2
INSERT INTO Reviews (user_id, book_id, review) VALUES
(3, 2, 'A timeless classic that everyone should read.'),
(4, 2, 'The moral lessons are powerful and still relevant today.');

-- Reviews for Book ID 3
INSERT INTO Reviews (user_id, book_id, review) VALUES
(5, 3, '1984 is a haunting portrayal of a dystopian future.'),
(6, 3, 'This book made me question the power structures in our society.');




